version: '0.1'
services:
# redis
  cache:
      container_name: cache
      image: redis:alpine
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning
      volumes: 
        - cache:/data
# sql test
  sql-server-test:
    container_name: sql-server-test
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1436:1433"
    environment:
      SA_PASSWORD: "123qwe!Q"
      ACCEPT_EULA: "Y"
# api test

# SSR test

# nginx test

volumes:
  cache:
    driver: local