// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyLfc.Persistence.AuthModel
{
    [DbContext(typeof(AuthLiverpoolContext))]
    public partial class AuthLiverpoolContextModel : RuntimeModel
    {
        static AuthLiverpoolContextModel()
        {
            var model = new AuthLiverpoolContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static AuthLiverpoolContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
