// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.Metadata;
using OpenIddict.EntityFrameworkCore.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace MyLfc.Persistence.AuthModel
{
    internal partial class OpenIddictEntityFrameworkCoreTokenintEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "OpenIddict.EntityFrameworkCore.Models.OpenIddictEntityFrameworkCoreToken<int>",
                typeof(OpenIddictEntityFrameworkCoreToken<int>),
                baseEntityType);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(int),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw);
            id.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            var applicationId = runtimeEntityType.AddProperty(
                "ApplicationId",
                typeof(int?),
                nullable: true);
            applicationId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var authorizationId = runtimeEntityType.AddProperty(
                "AuthorizationId",
                typeof(int?),
                nullable: true);
            authorizationId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var concurrencyToken = runtimeEntityType.AddProperty(
                "ConcurrencyToken",
                typeof(string),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetProperty("ConcurrencyToken", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetField("<ConcurrencyToken>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                concurrencyToken: true,
                maxLength: 50);
            concurrencyToken.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var creationDate = runtimeEntityType.AddProperty(
                "CreationDate",
                typeof(DateTime?),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetProperty("CreationDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetField("<CreationDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            creationDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var expirationDate = runtimeEntityType.AddProperty(
                "ExpirationDate",
                typeof(DateTime?),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetProperty("ExpirationDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetField("<ExpirationDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            expirationDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var payload = runtimeEntityType.AddProperty(
                "Payload",
                typeof(string),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetProperty("Payload", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetField("<Payload>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            payload.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var properties = runtimeEntityType.AddProperty(
                "Properties",
                typeof(string),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetProperty("Properties", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetField("<Properties>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            properties.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var redemptionDate = runtimeEntityType.AddProperty(
                "RedemptionDate",
                typeof(DateTime?),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetProperty("RedemptionDate", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetField("<RedemptionDate>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            redemptionDate.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var referenceId = runtimeEntityType.AddProperty(
                "ReferenceId",
                typeof(string),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetProperty("ReferenceId", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetField("<ReferenceId>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 100);
            referenceId.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var status = runtimeEntityType.AddProperty(
                "Status",
                typeof(string),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetProperty("Status", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetField("<Status>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50);
            status.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var subject = runtimeEntityType.AddProperty(
                "Subject",
                typeof(string),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetProperty("Subject", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetField("<Subject>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 400);
            subject.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var type = runtimeEntityType.AddProperty(
                "Type",
                typeof(string),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetProperty("Type", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetField("<Type>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true,
                maxLength: 50);
            type.AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { authorizationId });

            var index0 = runtimeEntityType.AddIndex(
                new[] { referenceId },
                unique: true);

            var index1 = runtimeEntityType.AddIndex(
                new[] { applicationId, status, subject, type });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("ApplicationId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType);

            var application = declaringEntityType.AddNavigation("Application",
                runtimeForeignKey,
                onDependent: true,
                typeof(OpenIddictEntityFrameworkCoreApplication<int>),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetProperty("Application", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetField("<Application>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var tokens = principalEntityType.AddNavigation("Tokens",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<OpenIddictEntityFrameworkCoreToken<int>>),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreApplication<int, OpenIddictEntityFrameworkCoreAuthorization<int>, OpenIddictEntityFrameworkCoreToken<int>>).GetProperty("Tokens", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreApplication<int, OpenIddictEntityFrameworkCoreAuthorization<int>, OpenIddictEntityFrameworkCoreToken<int>>).GetField("<Tokens>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("AuthorizationId") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("Id") }),
                principalEntityType);

            var authorization = declaringEntityType.AddNavigation("Authorization",
                runtimeForeignKey,
                onDependent: true,
                typeof(OpenIddictEntityFrameworkCoreAuthorization<int>),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetProperty("Authorization", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreToken<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreAuthorization<int>>).GetField("<Authorization>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var tokens = principalEntityType.AddNavigation("Tokens",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<OpenIddictEntityFrameworkCoreToken<int>>),
                propertyInfo: typeof(OpenIddictEntityFrameworkCoreAuthorization<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreToken<int>>).GetProperty("Tokens", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(OpenIddictEntityFrameworkCoreAuthorization<int, OpenIddictEntityFrameworkCoreApplication<int>, OpenIddictEntityFrameworkCoreToken<int>>).GetField("<Tokens>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "OpenIddictTokens");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
