export * from "./club-history.component";
export * from "./rules.component";
export * from "./sidebar-right.component";
export * from "./sidebar-left.component";
export * from "./about-club.component";
export * from "./about.component";
export * from "./copyright.component";
export * from "./squad.component";
export * from "./navbar.component";