export enum HelperType {
    EplTable = 1,
    BestPlayer = 2,
    Strikers = 3,
    Rules = 4,
    About = 5,
    Copyright = 6,
    Job = 7,
    ClubHistory = 8,
    AboutClub = 9,
    Instructions = 10,
    Plans = 11,
    Fantasy = 12,
    CupTable = 13,
    HeaderMatch = 14,
    Cooperation = 15,
    CurrentSeason = 16,
    RudWords = 17,
    WalMainInfo = 18
}
