name: Deploy-to-test

on:
  push:
    branches: [ master ]

jobs:

  run-script:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: restart test
      uses: fifsky/ssh-action@master
      with:
        command: |
          systemctl restart t
          ls -a
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }} 
        user: ${{ secrets.SSH_DEPLOY_USER }}
        key: ${{ secrets.SSH_DEPLOY_KEY }}
     
