name: Deploy-to-prod

on:
  release:
    types:
      - created
  push:
    branches:
      - 'releases/**'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: false
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
   # - name: Test
  #    run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish /home/runner/work/MyLFC/MyLFC/src/MyLfc.Web.WebHost/ -c Release --output ./artifacts/ -r linux-x64 --self-contained true -p:PublishSingleFile=false -p:PublishTrimmed=false -p:TrimMode=Link
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@v2.2.11
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          ARGS: "-avzr --delete --exclude=/wwwroot/ --exclude=/Logs/ --exclude '*.xml' --exclude 'appsettings.Production.json'"
          SOURCE: "/artifacts/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.SSH_DEPLOY_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }} 
          TARGET: ${{ secrets.SERVER_PROD_API_FOLDER }}
    - name: restart prod service
      uses: fifsky/ssh-action@master
      with:
        command: |
          systemctl restart p
        host: ${{ secrets.REMOTE_HOST }}
        port: ${{ secrets.REMOTE_PORT }} 
        user: ${{ secrets.SSH_DEPLOY_USER }}
        key: ${{ secrets.SSH_DEPLOY_KEY }}
